### ISSUE TITLE
can't yarn run electron:build in win x64

### ISSUE THREAD

**Issue by kendbad** [chrishham/BypassCors#3]
vue-cli-service electron:build --windows nsis --config electron-builder.json

![Screenshot_10](https://user-images.githubusercontent.com/106885376/172403305-b36d5e90-57ff-4064-ae85-eedd2fb69d9a.png)
 ERROR  Error: Application entry file "background.js" in the "C:\Users\kendb\BypassCors\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.
Error: Application entry file "background.js" in the "C:\Users\kendb\BypassCors\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.
    at error (C:\Users\kendb\BypassCors\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:7:12)
    at checkFileInArchive (C:\Users\kendb\BypassCors\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:33:11)
    at WinPackager.checkFileInPackage (C:\Users\kendb\BypassCors\node_modules\app-builder-lib\src\platformPackager.ts:402:7)
    at WinPackager.sanityCheckPackage (C:\Users\kendb\BypassCors\node_modules\app-builder-lib\src\platformPackager.ts:453:5)
    at WinPackager.doPack (C:\Users\kendb\BypassCors\node_modules\app-builder-lib\src\platformPackager.ts:242:5)
    at WinPackager.pack (C:\Users\kendb\BypassCors\node_modules\app-builder-lib\src\platformPackager.ts:114:5)
    at Packager.doBuild (C:\Users\kendb\BypassCors\node_modules\app-builder-lib\src\packager.ts:437:9)
    at executeFinally (C:\Users\kendb\BypassCors\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (C:\Users\kendb\BypassCors\node_modules\app-builder-lib\src\packager.ts:366:31)
    at Packager.build (C:\Users\kendb\BypassCors\node_modules\app-builder-lib\src\packager.ts:330:12)
    at executeFinally (C:\Users\kendb\BypassCors\node_modules\builder-util\src\promise.ts:12:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by chrishham** [comment]
@kendbad  i assign this issue to you.

**Comment by kendbad** [comment]
> @kendbad i assign this issue to you.
edit package.json
 + "electron:build": "vue-cli-service electron:build --windows nsis --config electron-builder.json",
 + "main": "dist_electron/bundled/background.js",

add file 

// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      // List native deps here if they don't work
      externals: ['electron-settings'],
      // If you are using Yarn Workspaces, you may have multiple node_modules folders
      // List them all here so that VCP Electron Builder can find them
      nodeModulesPath: ['../../node_modules', './node_modules']
    }
  }
}

**Comment by chrishham** [comment]
@kendbad congrats for resolving issue #3!
